%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.13 and Fixed-Point Designer 7.5           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function output = goertzel_filter_wrapper_fixpt(input_signal,N,target_freq,sample_freq)
    fm = get_fimath();
    input_signal_in = fi( input_signal, 1, 16, 0, fm );
    N_in = fi( N, 0, 8, 0, fm );
    target_freq_in = fi( target_freq, 0, 18, 0, fm );
    sample_freq_in = fi( sample_freq, 0, 22, 0, fm );
    [output_out] = goertzel_filter_fixpt( input_signal_in, N_in, target_freq_in, sample_freq_in );
    output = double( output_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
